version: '2'
services:
  rocketchat:
    image: cloyne/rocketchat
    build: .
    container_name: rocketchat
    networks:
      server3:
        ipv4_address: '172.25.0.2'
    environment:
      VIRTUAL_HOST: chat.cloyne.org
      MONGO_URL: mongodb://mongo:27017/rocketchat
      MONGO_OPLOG_URL: mongodb://mongo:27017/local?replSet=rs01
      ROOT_URL: https://chat.cloyne.org
      Accounts_UseDNSDomainCheck: "False"
    volumes:
      - ./var/log/nginx:/var/log/nginx
      - ./etc/ssl:/ssl
      - ./etc/nginx/sites:/etc/nginx/sites-volume
      - ./var/log/dnsmasq:/var/log/dnsmasq
      - ./var/log/dockergen:/var/log/dockergen
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    links:
        - mongo:mongo

  mongo:
    image: cloyne/mongodb:3.6
    container_name: mongo
    networks:
      server3:
        ipv4_address: '172.25.0.3'
    volumes:
      - ./data/runtime/mongo:/data/db
      - ./data/dump:/dump
    command: mongod --smallfiles

networks:
  server3:
    driver: bridge
    ipam:
      config:
        - subnet: '172.25.0.0/24'
